format = """
$all\
$custom\
$line_break\
$time\
$character"""
add_newline = false

[time]
disabled = false
time_format = '%T'
style = 'bold yellow'

[directory]
truncation_length = 0
truncate_to_repo = false
home_symbol = "~"

[gcloud]
format = '($symbol  [$project]($style) )'
symbol = 'on ☁️'
style = 'bold blue'
